### ISSUE TITLE
Skip re-installing already installed plugin

### ISSUE THREAD

**Issue by duyphuongn** [auvred/prettier-pnp#4]
Hello. Thank you for your plugin. 

I was able to run Prettier v3 with [`@prettier/plugin-php` 0.20.0](https://github.com/prettier/plugin-php/tree/main).

```sh
npx prettier-pnp --pnp @prettier/plugin-php --ignore-path .prettierignore -c "**/*.php"
```

However, it keeps re-installing the plugin every run although it's been already installed. 

Can you add a check to skip this part? 

Thank you.

**Comment by auvred** [comment]
Hi! Thank you for your interest in this project. I was already thinking of implementing something like this, but I postponed it. Now I think it's time to do it!

**Comment by auvred** [comment]
Released it https://github.com/auvred/prettier-pnp/releases/tag/v0.2.0
