### ISSUE TITLE
Can't get rid of extra output

### ISSUE THREAD

**Issue by imericxu** [auvred/prettier-pnp#9]
I'm trying to run this with `null-ls.nvim` and there doesn't seem to be an option to disable extra output from `prettier-pnp`.

I'm trying to remove the output:
```
----- Already installed ----

 - prettier-plugin-my-plugin

----- Running prettier -----
```

**Comment by auvred** [comment]
Hi! Now you can pass `--quiet` arg, it will prevent any extra output

**Comment by imericxu** [comment]
Wow that was fast, tysm!
